networks:
  net:
    driver: bridge
  # test:
  #   external: true  # не забыть объявить до запуска скрипта

volumes:
  prometheus-storage:
  grafana-storage:

services:
  #
  # балансировщик для нескольких бекендов "social_srv"
  #
  nginx_lb:
    image: nginx:1.28.0-alpine
    container_name: "nginx_lb"
    hostname: "nginx_lb"
    # restart: on-failure
    depends_on:
      - social_srv1
      - social_srv2
    volumes:
      - ./load_balancing/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net
    ports:
      - 8091:80                               # посмотреть статус nginx
      - ${ENV_SOCIAL_HTTP_EXTERNAL_PORT}:8080 # балансировка social_srv


  social_srv1:
    image: ${ENV_SOCIAL_SERVICE_IMAGE}
    container_name: "social_srv1"
    hostname: "social_srv1"
    restart: no       # always, on-failure, unless-stopped, no (by default)
    depends_on:
      - haproxy_lb
      - kafka
      - chat_srv
    environment:
      - PGSQL_MASTER_URL=postgresql://${ENV_POSTGRES_USER}:${ENV_POSTGRES_PASSWORD}@haproxy_lb:8080/postgres
      - PGSQL_REPLICA_URL=postgresql://${ENV_POSTGRES_USER}:${ENV_POSTGRES_PASSWORD}@haproxy_lb:8081/postgres
      - GRPC_URL=grpc://chat_srv:50051
      - KAFKA_URL=tcp://kafka:9092
      - HTTP_LISTENING=0.0.0.0:6000
      - HTTP_QUEUE_CAPACITY=4096
      - HTTP_THREADS_COUNT=1
      - PROMETHEUS_PORT=6001
    networks:
      - net
    # ports:
      # - ${ENV_SOCIAL_HTTP_EXTERNAL_PORT}:6000
      # - ${ENV_SOCIAL_PROM_EXTERNAL_PORT}:6001   # для метрик Prometheus


  social_srv2:
    image: ${ENV_SOCIAL_SERVICE_IMAGE}
    container_name: "social_srv2"
    hostname: "social_srv2"
    restart: no       # always, on-failure, unless-stopped, no (by default)
    depends_on:
      - haproxy_lb
      - kafka
      - chat_srv
    environment:
      - PGSQL_MASTER_URL=postgresql://${ENV_POSTGRES_USER}:${ENV_POSTGRES_PASSWORD}@haproxy_lb:8080/postgres
      - PGSQL_REPLICA_URL=postgresql://${ENV_POSTGRES_USER}:${ENV_POSTGRES_PASSWORD}@haproxy_lb:8081/postgres
      - GRPC_URL=grpc://chat_srv:50051
      - KAFKA_URL=tcp://kafka:9092
      - HTTP_LISTENING=0.0.0.0:6000
      - HTTP_QUEUE_CAPACITY=4096
      - HTTP_THREADS_COUNT=1
      - PROMETHEUS_PORT=6001
    networks:
      - net
    # ports:
      # - ${ENV_SOCIAL_HTTP_EXTERNAL_PORT}:6000
      # - ${ENV_SOCIAL_PROM_EXTERNAL_PORT}:6001   # для метрик Prometheus


  #
  # балансировщик для нескольких бекендов "postgres"
  #
  haproxy_lb:
    image: haproxy:2.4.29-alpine
    container_name: "haproxy_lb"
    hostname: "haproxy_lb"
    # restart: on-failure
    depends_on:
      postgres_db:
        condition: service_healthy
      postgres_r1:
        condition: service_healthy
      postgres_r2:
        condition: service_healthy
    volumes:
      - ./load_balancing/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - net
    ports:
      - 8092:80                                     # посмотреть статус haproxy
      - ${ENV_POSTGRES_MASTER_EXTERNAL_PORT}:8080   # балансировка postgres (master)
      - ${ENV_POSTGRES_REPLICA_EXTERNAL_PORT}:8081  # балансировка postgres (replicas)


  postgres_db:
    image: postgres:16-alpine
    container_name: "postgres_db"
    hostname: "postgres_db"
    restart: no       # always, on-failure, unless-stopped, no (by default)
    environment:
      - POSTGRES_USER=${ENV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}
    volumes:
      - ./postgresql/load_balancing/postgres_m0_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net
    # ports:
    #   - 15432:5432


  postgres_r1:
    image: postgres:16-alpine
    container_name: "postgres_r1"
    hostname: "postgres_r1"
    restart: no       # always, on-failure, unless-stopped, no (by default)
    environment:
      - POSTGRES_USER=${ENV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}
    volumes:
      - ./postgresql/load_balancing/postgres_r1_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net
    # ports:
    #   - 25432:5432


  postgres_r2:
    image: postgres:16-alpine
    container_name: "postgres_r2"
    hostname: "postgres_r2"
    restart: no       # always, on-failure, unless-stopped, no (by default)
    environment:
      - POSTGRES_USER=${ENV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}
    volumes:
      - ./postgresql/load_balancing/postgres_r2_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net
    # ports:
    #   - 35432:5432


  chat_srv:
    image: ${ENV_CHAT_SERVICE_IMAGE}
    container_name: "chat_srv"
    hostname: "chat_srv"
    # restart: on-failure
    depends_on:
      tarantool_db:
        condition: service_started
    environment:
      - TARANTOOL_URL=tcp://tntuser:tntpass@tarantool_db:3301
      - GRPC_LISTENING=0.0.0.0:50051
      - HTTP_LISTENING=0.0.0.0:6000
      - HTTP_QUEUE_CAPACITY=4096
      - HTTP_THREADS_COUNT=1
      - PROMETHEUS_PORT=6001
    networks:
      - net
    ports:
      - ${ENV_CHAT_HTTP_EXTERNAL_PORT}:6000
      # - ${ENV_CHAT_PROM_EXTERNAL_PORT}:6001   # для метрик Prometheus


  ws_srv:
    image: ${ENV_WS_SERVICE_IMAGE}
    container_name: "ws_srv"
    hostname: "ws_srv"
    # restart: on-failure
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=tcp://kafka:9092
      - HTTP_LISTENING=0.0.0.0:6000
      - HTTP_QUEUE_CAPACITY=4096
      - HTTP_THREADS_COUNT=1
      - PROMETHEUS_PORT=6001
    networks:
      - net
    ports:
      - ${ENV_WS_HTTP_EXTERNAL_PORT}:6000
      # - ${ENV_WS_PROM_EXTERNAL_PORT}:6001   # для метрик Prometheus


  kafka:
    image: bitnami/kafka:3.9.0
    container_name: "kafka"
    hostname: "kafka"
    # restart: on-failure
    environment:
      # KRaft
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Config parameters
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=10
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_CFG_RETENTION_MS=604800000
      - KAFKA_CFG_BACKGROUND_THREADS=3
    networks:
      - net
    ports:
      - 9092:9092


  kafka_ui:
    image: provectuslabs/kafka-ui:v0.4.0
    container_name: "kafka_ui"
    hostname: "kafka_ui"
    # restart: on-failure
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_NAME=kraft
    networks:
      - net
    ports:
      - 8090:8080


  tarantool_db:
    build:
      context: ./tarantool/
      dockerfile: Dockerfile
    container_name: "tarantool_db"
    hostname: "tarantool_db"
    # restart: on-failure
    volumes:
      - ./tarantool/scripts:/opt/tarantool
    networks:
      - net
    ports:
      - 3301:3301
      - 8081:8081 # админка
    command: tarantool /opt/tarantool/udf.lua


  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: "prometheus"
    hostname: "prometheus"
    restart: unless-stopped
    networks:
      - net
    ports:
      - 9090:9090
      # - 9091:9091 # Pushgateway
      # - 9093:9093 # Alertmanager
      # - 9094:9094 # Alertmanager clustering
      # - 9100:9100 # Prometheus Exporters (9100-9563)
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--enable-feature=promql-experimental-functions'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-remote-write-receiver' # Enables remote write endpoint for k6


  grafana:
    image: grafana/grafana
    container_name: "grafana"
    hostname: "grafana"
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
    depends_on:
      - prometheus
    networks:
      - net
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-storage:/var/lib/grafana


  node_exporter:
    image: prom/node-exporter
    container_name: "node_exporter"
    hostname: "node_exporter"
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - net
    expose:
      - 9100


  cadvisor:
    image: google/cadvisor
    container_name: "cadvisor"
    hostname: "cadvisor"
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - net
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro


  k6:
    image: grafana/k6
    container_name: "k6"
    hostname: "k6"
    # restart: always
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_STATS=p(95),p(99),min,max,count,sum
      - TEST_HOST=http://nginx_lb:8080
    depends_on:
      - prometheus
      - nginx_lb
    networks:
      - net
    volumes:
      - ./k6_tests:/tests
    # command: run --verbose --out experimental-prometheus-rw --http-debug="full" /tests/user_search.js
