networks:
  net:
    driver: bridge

services:
  social_srv:
    image: ${ENV_SOCIAL_SERVICE_IMAGE}
    container_name: "social_srv"
    hostname: "social_srv"
    # restart: on-failure
    depends_on:
      postgres_db:
        condition: service_healthy
      tarantool_db:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      - PGSQL_MASTER_URL=postgresql://postgres:${ENV_POSTGRES_PASSWORD}@postgres_db:5432/postgres
      - GRPC_URL=grpc://chat_srv:50051
      - KAFKA_URL=tcp://kafka:9092
      - HTTP_LISTENING=0.0.0.0:6000
      - HTTP_QUEUE_CAPACITY=4096
      - HTTP_THREADS_COUNT=1
      - PROMETHEUS_PORT=6001
    networks:
      - net
    ports:
      - ${ENV_SOCIAL_HTTP_EXTERNAL_PORT}:6000
      # - ${ENV_SOCIAL_PROM_EXTERNAL_PORT}:6001   # для метрик Prometheus


  chat_srv:
    image: ${ENV_CHAT_SERVICE_IMAGE}
    container_name: "chat_srv"
    hostname: "chat_srv"
    # restart: on-failure
    depends_on:
      postgres_db:
        condition: service_healthy
      tarantool_db:
        condition: service_started
    environment:
      - TARANTOOL_URL=tcp://tntuser:tntpass@tarantool_db:3301
      - GRPC_LISTENING=0.0.0.0:50051
      - HTTP_LISTENING=0.0.0.0:6000
      - HTTP_QUEUE_CAPACITY=4096
      - HTTP_THREADS_COUNT=1
      - PROMETHEUS_PORT=6001
    networks:
      - net
    ports:
      - ${ENV_CHAT_HTTP_EXTERNAL_PORT}:6000
      # - ${ENV_CHAT_PROM_EXTERNAL_PORT}:6001   # для метрик Prometheus


  ws_srv1:
    image: ${ENV_WS_SERVICE_IMAGE}
    container_name: "ws_srv1"
    hostname: "ws_srv1"
    # restart: on-failure
    depends_on:
      - kafka
      - social_srv
    environment:
      - KAFKA_URL=tcp://kafka:9092
      - HTTP_LISTENING=0.0.0.0:6000
      - HTTP_QUEUE_CAPACITY=4096
      - HTTP_THREADS_COUNT=1
      - PROMETHEUS_PORT=6001
    networks:
      - net
    # ports:
    #   - ${ENV_WS_HTTP_EXTERNAL_PORT}:6000
    #   # - ${ENV_WS_PROM_EXTERNAL_PORT}:6001   # для метрик Prometheus


  ws_srv2:
    image: ${ENV_WS_SERVICE_IMAGE}
    container_name: "ws_srv2"
    hostname: "ws_srv2"
    # restart: on-failure
    depends_on:
      - kafka
      - social_srv
    environment:
      - KAFKA_URL=tcp://kafka:9092
      - HTTP_LISTENING=0.0.0.0:6000
      - HTTP_QUEUE_CAPACITY=4096
      - HTTP_THREADS_COUNT=1
      - PROMETHEUS_PORT=6001
    networks:
      - net


  ws_srv3:
    image: ${ENV_WS_SERVICE_IMAGE}
    container_name: "ws_srv3"
    hostname: "ws_srv3"
    # restart: on-failure
    depends_on:
      - kafka
      - social_srv
    environment:
      - KAFKA_URL=tcp://kafka:9092
      - HTTP_LISTENING=0.0.0.0:6000
      - HTTP_QUEUE_CAPACITY=4096
      - HTTP_THREADS_COUNT=1
      - PROMETHEUS_PORT=6001
    networks:
      - net


  nginx:
    image: nginx:1.28.0-alpine
    container_name: "nginx"
    hostname: "nginx"
    # restart: on-failure
    depends_on:
      - ws_srv1
      - ws_srv2
      - ws_srv3
    volumes:
      - ./ws_queue/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net
    ports:
      - 8080:80


  kafka:
    image: bitnami/kafka:3.9.0
    container_name: "kafka"
    hostname: "kafka"
    # restart: on-failure
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # KAFKA_BROKER_ID: 1
      # KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - net
    ports:
      - 9092:9092


  kafka_ui:
    image: provectuslabs/kafka-ui:v0.4.0
    container_name: "kafka_ui"
    hostname: "kafka_ui"
    # restart: on-failure
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_NAME=kraft
    networks:
      - net
    ports:
      - 8090:8080


  postgres_db:
    image: postgres:16-alpine
    container_name: "postgres_db"
    hostname: "postgres_db"
    # restart: on-failure
    environment:
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}
    volumes:
      - ./postgresql/single:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net
    ports:
      - 15432:5432


  tarantool_db:
    # image: tarantool/tarantool:2.11
    # image: tarantool/tarantool:3.3.2
    build:
      context: ./tarantool/
      dockerfile: Dockerfile
    container_name: "tarantool_db"
    hostname: "tarantool_db"
    # restart: on-failure
    # depends_on:
    #   postgres_db:
    #     condition: service_healthy
    volumes:
      - ./tarantool/scripts:/opt/tarantool
      # - ./tarantool/tarantool_volume:/var/lib/tarantool
      # - tarantool_storage:/var/lib/tarantool
    networks:
      - net
    ports:
      - "3301:3301"
      - "8081:8081" # админка
    command: tarantool /opt/tarantool/udf.lua
