networks:
  net:
    driver: bridge
  # test:
  #   external: true  # не забыть объявить до запуска скрипта

volumes:
  prometheus-storage:
  grafana-storage:
  etcd-0-data:
  etcd-1-data:
  etcd-2-data:
  patroni-0-data:
  patroni-1-data:
  patroni-2-data:

services:
  #
  # кластер распределенной системы хранения конфигурации (DCS)
  # в виде узлов etcd, обеспечиваем кворум
  #
  etcd0:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: "etcd0"
    hostname: "etcd0"
    # restart: on-failure
    environment:
      - ETCD_NAME=etcd0
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd0:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_ENABLE_V2=true
      - ETCD_ELECTION_TIMEOUT=1000
      - ETCD_HEARTBEAT_INTERVAL=100
      - ETCD_DATA_DIR=/etcd_data
    volumes:
      - etcd-0-data:/etcd_data
    networks:
      - net
    ports:
      - 2379:2379


  etcd1:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: "etcd1"
    hostname: "etcd1"
    # restart: on-failure
    environment:
      - ETCD_NAME=etcd1
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_ENABLE_V2=true
      - ETCD_ELECTION_TIMEOUT=1000
      - ETCD_HEARTBEAT_INTERVAL=100
      - ETCD_DATA_DIR=/etcd_data
    volumes:
      - etcd-1-data:/etcd_data
    networks:
      - net
    # ports:
    #   - 2379:2379


  etcd2:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: "etcd2"
    hostname: "etcd2"
    # restart: on-failure
    environment:
      - ETCD_NAME=etcd2
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_ENABLE_V2=true
      - ETCD_ELECTION_TIMEOUT=1000
      - ETCD_HEARTBEAT_INTERVAL=100
      - ETCD_DATA_DIR=/etcd_data
    volumes:
      - etcd-2-data:/etcd_data
    networks:
      - net
    # ports:
    #   - 2379:2379


  #
  # кластер системы управления распределенными базами PostgreSQL
  # в виде узлов PostgreSQL под управлением Patroni
  #
  pg_patroni0:
    build:
      context: ./load_balancing/patroni/
      dockerfile: Dockerfile
    container_name: "pg_patroni0"
    hostname: "pg_patroni0"
    restart: no       # always, on-failure, unless-stopped, no (by default)
    # environment: # настройки можно применять через ENV или файлом patroni.yml
      # - PATRONI_SCOPE=patroni-cluster
      # - PATRONI_NAME=pg_patroni0
      # - PATRONI_RESTAPI_CONNECT_ADDRESS=pg_patroni0:8008
      # - PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      # - PATRONI_ETCD_HOSTS=etcd0:2379,etcd1:2379,etcd2:2379
      # - PATRONI_POSTGRESQL_CONNECT_ADDRESS=pg_patroni0:5432
      # - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      # - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      # - PATRONI_POSTGRESQL_PGPASS=/tmp/pgpass
      # - PATRONI_SUPERUSER_USERNAME=${ENV_POSTGRES_USER}
      # - PATRONI_SUPERUSER_PASSWORD=${ENV_POSTGRES_PASSWORD}
      # - PATRONI_REPLICATION_USERNAME=replicator
      # - PATRONI_REPLICATION_PASSWORD=rpass
    depends_on:
      - etcd0
      - etcd1
      - etcd2
    volumes:
      - patroni-0-data:/var/lib/postgresql/data
      - ./load_balancing/patroni/patroni_0.yml:/etc/patroni/patroni.yml
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net
    ports:
      - 5400:5432
      - 8008:8008


  pg_patroni1:
    build:
      context: ./load_balancing/patroni/
      dockerfile: Dockerfile
    container_name: "pg_patroni1"
    hostname: "pg_patroni1"
    restart: no       # always, on-failure, unless-stopped, no (by default)
    # environment: # настройки можно применять через ENV или файлом patroni.yml
      # - PATRONI_SCOPE=patroni-cluster
      # - PATRONI_NAME=pg_patroni1
      # - PATRONI_RESTAPI_CONNECT_ADDRESS=pg_patroni1:8008
      # - PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      # - PATRONI_ETCD_HOSTS=etcd0:2379,etcd1:2379,etcd2:2379
      # - PATRONI_POSTGRESQL_CONNECT_ADDRESS=pg_patroni1:5432
      # - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      # - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      # - PATRONI_POSTGRESQL_PGPASS=/tmp/pgpass
      # - PATRONI_SUPERUSER_USERNAME=${ENV_POSTGRES_USER}
      # - PATRONI_SUPERUSER_PASSWORD=${ENV_POSTGRES_PASSWORD}
      # - PATRONI_REPLICATION_USERNAME=replicator
      # - PATRONI_REPLICATION_PASSWORD=rpass
    depends_on:
      - etcd0
      - etcd1
      - etcd2
      - pg_patroni0
    volumes:
      - patroni-1-data:/var/lib/postgresql/data
      - ./load_balancing/patroni/patroni_1.yml:/etc/patroni/patroni.yml
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net
    ports:
      - 5401:5432
      - 8018:8008


  pg_patroni2:
    build:
      context: ./load_balancing/patroni/
      dockerfile: Dockerfile
    container_name: "pg_patroni2"
    hostname: "pg_patroni2"
    restart: no       # always, on-failure, unless-stopped, no (by default)
    # environment: # настройки можно применять через ENV или файлом patroni.yml
      # - PATRONI_SCOPE=patroni-cluster
      # - PATRONI_NAME=pg_patroni2
      # - PATRONI_RESTAPI_CONNECT_ADDRESS=pg_patroni2:8008
      # - PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      # - PATRONI_ETCD_HOSTS=etcd0:2379,etcd1:2379,etcd2:2379
      # - PATRONI_POSTGRESQL_CONNECT_ADDRESS=pg_patroni2:5432
      # - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      # - PATRONI_POSTGRESQL_DATA_DIR=/var/lib/postgresql/data
      # - PATRONI_POSTGRESQL_PGPASS=/tmp/pgpass
      # - PATRONI_SUPERUSER_USERNAME=${ENV_POSTGRES_USER}
      # - PATRONI_SUPERUSER_PASSWORD=${ENV_POSTGRES_PASSWORD}
      # - PATRONI_REPLICATION_USERNAME=replicator
      # - PATRONI_REPLICATION_PASSWORD=rpass
    depends_on:
      - etcd0
      - etcd1
      - etcd2
      - pg_patroni0
      - pg_patroni1
    volumes:
      - patroni-2-data:/var/lib/postgresql/data
      - ./load_balancing/patroni/patroni_2.yml:/etc/patroni/patroni.yml
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net
    ports:
      - 5402:5432
      - 8028:8008


  #
  # балансировщик нагрузки на распределенную систему Patroni
  #
  haproxy_lb:
    image: haproxy:2.4.29-alpine
    container_name: "haproxy_lb"
    hostname: "haproxy_lb"
    # restart: on-failure
    depends_on:
      pg_patroni0:
        condition: service_healthy
      pg_patroni1:
        condition: service_healthy
      pg_patroni2:
        condition: service_healthy
    volumes:
      - ./load_balancing/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - net
    ports:
      - 8180:8404                                   # посмотреть статус haproxy
      - ${ENV_POSTGRES_MASTER_EXTERNAL_PORT}:5000   # балансировка postgres (master)
      - ${ENV_POSTGRES_REPLICA_EXTERNAL_PORT}:5001  # балансировка postgres (replicas)


  #
  # балансировщик для нескольких бекендов "social_srv"
  #
  nginx_lb:
    image: nginx:1.28.0-alpine
    container_name: "nginx_lb"
    hostname: "nginx_lb"
    # restart: on-failure
    depends_on:
      - social_srv1
      - social_srv2
    volumes:
      - ./load_balancing/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net
    ports:
      - 8280:8404                             # посмотреть статус nginx
      - ${ENV_SOCIAL_HTTP_EXTERNAL_PORT}:8080 # балансировка social_srv


  social_srv1:
    image: ${ENV_SOCIAL_SERVICE_IMAGE}
    container_name: "social_srv1"
    hostname: "social_srv1"
    restart: no       # always, on-failure, unless-stopped, no (by default)
    depends_on:
      - haproxy_lb
      - kafka
      - chat_srv
    environment:
      - PGSQL_MASTER_URL=postgresql://${ENV_POSTGRES_USER}:${ENV_POSTGRES_PASSWORD}@haproxy_lb:5000/postgres
      - PGSQL_REPLICA_URL=postgresql://${ENV_POSTGRES_USER}:${ENV_POSTGRES_PASSWORD}@haproxy_lb:5001/postgres
      - GRPC_URL=grpc://chat_srv:50051
      - KAFKA_URL=tcp://kafka:9092
      - HTTP_LISTENING=0.0.0.0:6000
      - HTTP_QUEUE_CAPACITY=4096
      - HTTP_THREADS_COUNT=1
      - PROMETHEUS_PORT=6001
    networks:
      - net
    # ports:
      # - ${ENV_SOCIAL_HTTP_EXTERNAL_PORT}:6000
      # - ${ENV_SOCIAL_PROM_EXTERNAL_PORT}:6001   # для метрик Prometheus


  social_srv2:
    image: ${ENV_SOCIAL_SERVICE_IMAGE}
    container_name: "social_srv2"
    hostname: "social_srv2"
    restart: no       # always, on-failure, unless-stopped, no (by default)
    depends_on:
      - haproxy_lb
      - kafka
      - chat_srv
    environment:
      - PGSQL_MASTER_URL=postgresql://${ENV_POSTGRES_USER}:${ENV_POSTGRES_PASSWORD}@haproxy_lb:5000/postgres
      - PGSQL_REPLICA_URL=postgresql://${ENV_POSTGRES_USER}:${ENV_POSTGRES_PASSWORD}@haproxy_lb:5001/postgres
      - GRPC_URL=grpc://chat_srv:50051
      - KAFKA_URL=tcp://kafka:9092
      - HTTP_LISTENING=0.0.0.0:6000
      - HTTP_QUEUE_CAPACITY=4096
      - HTTP_THREADS_COUNT=1
      - PROMETHEUS_PORT=6001
    networks:
      - net
    # ports:
      # - ${ENV_SOCIAL_HTTP_EXTERNAL_PORT}:6000
      # - ${ENV_SOCIAL_PROM_EXTERNAL_PORT}:6001   # для метрик Prometheus


  chat_srv:
    image: ${ENV_CHAT_SERVICE_IMAGE}
    container_name: "chat_srv"
    hostname: "chat_srv"
    # restart: on-failure
    depends_on:
      tarantool_db:
        condition: service_started
    environment:
      - TARANTOOL_URL=tcp://tntuser:tntpass@tarantool_db:3301
      - GRPC_LISTENING=0.0.0.0:50051
      - HTTP_LISTENING=0.0.0.0:6000
      - HTTP_QUEUE_CAPACITY=4096
      - HTTP_THREADS_COUNT=1
      - PROMETHEUS_PORT=6001
    networks:
      - net
    ports:
      - ${ENV_CHAT_HTTP_EXTERNAL_PORT}:6000
      # - ${ENV_CHAT_PROM_EXTERNAL_PORT}:6001   # для метрик Prometheus


  ws_srv:
    image: ${ENV_WS_SERVICE_IMAGE}
    container_name: "ws_srv"
    hostname: "ws_srv"
    # restart: on-failure
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=tcp://kafka:9092
      - HTTP_LISTENING=0.0.0.0:6000
      - HTTP_QUEUE_CAPACITY=4096
      - HTTP_THREADS_COUNT=1
      - PROMETHEUS_PORT=6001
    networks:
      - net
    ports:
      - ${ENV_WS_HTTP_EXTERNAL_PORT}:6000
      # - ${ENV_WS_PROM_EXTERNAL_PORT}:6001   # для метрик Prometheus


  kafka:
    image: bitnami/kafka:3.9.0
    container_name: "kafka"
    hostname: "kafka"
    # restart: on-failure
    environment:
      # KRaft
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Config parameters
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=10
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_CFG_RETENTION_MS=604800000
      - KAFKA_CFG_BACKGROUND_THREADS=3
    networks:
      - net
    ports:
      - 9092:9092


  kafka_ui:
    image: provectuslabs/kafka-ui:v0.4.0
    container_name: "kafka_ui"
    hostname: "kafka_ui"
    # restart: on-failure
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_NAME=kraft
    networks:
      - net
    ports:
      - 8090:8080


  tarantool_db:
    build:
      context: ./tarantool/
      dockerfile: Dockerfile
    container_name: "tarantool_db"
    hostname: "tarantool_db"
    # restart: on-failure
    volumes:
      - ./tarantool/scripts:/opt/tarantool
    networks:
      - net
    ports:
      - 3301:3301
      - 8081:8081 # админка
    command: tarantool /opt/tarantool/udf.lua


  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: "prometheus"
    hostname: "prometheus"
    restart: unless-stopped
    networks:
      - net
    ports:
      - 9090:9090
      # - 9091:9091 # Pushgateway
      # - 9093:9093 # Alertmanager
      # - 9094:9094 # Alertmanager clustering
      # - 9100:9100 # Prometheus Exporters (9100-9563)
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--enable-feature=promql-experimental-functions'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-remote-write-receiver' # Enables remote write endpoint for k6


  grafana:
    image: grafana/grafana
    container_name: "grafana"
    hostname: "grafana"
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
    depends_on:
      - prometheus
    networks:
      - net
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-storage:/var/lib/grafana


  node_exporter:
    image: prom/node-exporter
    container_name: "node_exporter"
    hostname: "node_exporter"
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - net
    expose:
      - 9100


  cadvisor:
    image: google/cadvisor
    container_name: "cadvisor"
    hostname: "cadvisor"
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - net
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro


  k6:
    image: grafana/k6
    container_name: "k6"
    hostname: "k6"
    # restart: always
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_STATS=p(95),p(99),min,max,count,sum
      - TEST_HOST=http://nginx_lb:8080
    depends_on:
      - prometheus
      - nginx_lb
    networks:
      - net
    volumes:
      - ./k6_tests:/tests
    # command: run --verbose --out experimental-prometheus-rw --http-debug="full" /tests/user_search.js
