# по идее можно добавлять кастомные метрики, например,
# если реализовать http-endpoints и возвращать JSON с метриками
# но тогда надо убедиться, что в контейнере агента установлен curl и jq

# UserParameter=chat_service.connections.active, curl -s http://chat_srv:6001/info | jq '.connections_active'
# UserParameter=chat_service.messages.rate, curl -s http://chat_srv:6001/info | jq '.messages_per_minute'
