FROM alpine:3.19.7

LABEL org.opencontainers.image.version="@SERVICE_VERSION@"

RUN apk update \
 && apk add libstdc++ libpq libuuid ossp-uuid-libs libgrpc grpc-cpp protobuf \
 && rm -rf /var/cache/apk/*

WORKDIR /service
COPY bin/@SERVICE_TARGET@ /service
ENTRYPOINT ["./@SERVICE_TARGET@"]
