global:
  scrape_interval: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'  # Self-monitoring
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
    metrics_path: /metrics

  - job_name: 'social'
    static_configs:
      - targets: ['social_srv:6001']
    metrics_path: /metrics
