global:
  scrape_interval: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'  # Self-monitoring
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporterr'
    static_configs:
      - targets: ['node_exporter:9100']
    metrics_path: /metrics

  - job_name: 'cadvisor'  # Container Advisor
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics

  - job_name: 'social'
    static_configs:
      - targets: ['social_srv:6001']
    metrics_path: /metrics
