events {
    worker_connections  1024;
}

http {
    upstream backend_servers {
        # balancing method by default is round-robin
        least_conn;
        server  social_srv1:6000    fail_timeout=1s max_fails=1;
        server  social_srv2:6000    fail_timeout=1s max_fails=1;
    }

    server {
        listen 8404;

        location /stats {
            stub_status;
            allow 127.0.0.1;
            allow 10.0.0.0/8;
            allow 172.16.0.0/12;
            allow 192.168.0.0/16;
            deny all;
        }
    }

    server {
        listen 8080;

        server_name     localhost nginx_lb.test;

        location / {
            proxy_connect_timeout               5s;
            proxy_send_timeout                  65s;
            proxy_read_timeout                  65s;
            proxy_pass                          http://backend_servers;
            proxy_set_header Host               $host;
            proxy_set_header X-Real-IP          $remote_addr;
            proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto  $scheme;
        }
    }
}
